

title: Matthew Rose
email: me@matthewaerose.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Matthew Rose, a dedicated Site Reliability Engineer (SRE) and 
  DevOps enthusiast. With a solid foundation in both software development 
  and system administration, I excel at creating efficient and automated 
  solutions for complex infrastructure challenges
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matthewaerose.com" # the base hostname & protocol for your site, e.g. http://example.com

domain: matthewaerose.com
github_username: matthewaerose

remote_theme: mmistakes/minimal-mistakes@4.27.1

plugins:
  - jekyll-feed
  - jekyll-include-cache

timezone: America/Chicago

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-R90CZ79KH4"
    anonymize_ip: false # default

minimal_mistakes_skin: "dark"

social-network-links:
  rss: true
  github: matthewaerose
  mastodon: mas.to/@kephalos
  linkedin: matthewaerose

rss-description: "Matthew Rose's Blog"

# Navigation
navbar-links:
  home: "index"
  blog: "blog"
  resume: "resume"
  contact: "contact"

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name: Matthew Rose
  location: Florence, AL
  avatar: /assets/images/self.png
  bio: >
    Pianist turned Site Reliability Engineer.
    Ask me about my cats.
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/matthewaerose.bsky.social"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matthewaerose"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthewaerose"


footer:
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/matthewaerose.bsky.social"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matthewaerose"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthewaerose"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
